// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const FirebaseOptions currentPlatform = FirebaseOptions(
    apiKey: 'AIzaSyCI3h3A1uxm30VHhZSXoEPDFY4auQlMelY',
    authDomain: 'celiapp-c2239.firebaseapp.com',
    projectId: 'celiapp-c2239',
    storageBucket: 'celiapp-c2239.appspot.com',
    messagingSenderId: '360503101068',
    appId: '1:360503101068:android:ef0b12072372ba0fc59da9',
    measurementId: 'G-PXJK7NKRE5', // Si estás utilizando Google Analytics, asegúrate de incluir este ID
  );
}